export const strings = {
  Home: {
    introTitle: "Host, Connect, Celebrate: Your Events, Our Platform!",
    introSubtitle:
      "Book and learn helpful tips from 3,168+ mentors in world-class companies with our global community.",
    exploreButton: "Explore Now",
    trustedByEventsTitleOne: "Trusted by",
    trustedByEventsTitleTwo: "thousands of Events",
    emptyCollectionTitle: "No Events Found!",
    emptyCollectionSubtitle: "Come back later",
  },
  CreateEvent: {
    createEventTitle: "Create Event",
    updateEventTitle: "Update Event",
    addNewCategory: "Add New Category",
    alertDialogTitle: "New Category",
    alertDialogCancel: "Cancel",
    alertDialogAdd: "Add",
    fileUploadTitle: "Drag photo here",
    fileUploadTypes: "SVG, PNG, JPG",
    fileUploadButton: "Select from computer",
    startDateTitle: "Start Date:",
    endDateTitle: "End Date:",
    freeTicketTitle: "Free Ticket",
    formSubmitButton: "Submitting...",
  },
  EventDetails: {
    isFree: "FREE",
    descriptionTitle: "What You'll Learn:",
    noTicketsTitle: "Sorry, tickets are no longer available.",
    getTicketsButton: "Get Tickets",
    getTicketButton: "Get Ticket",
    buyTicketButton: "Buy Ticket",
  },
  EventCard: {
    orderDetailsTitle: "Order Details",
    alertDialogTitle: "Are you sure you want to delete?",
    alertDialogSubtitle: "This will permanently delete this event",
    alertDialogCancel: "Cancel",
    alertDialogDelete: "Delete",
    alertDialogDeleting: "Deleting...",
    relatedEventsTitle: "Related Events",
  },
  Profile: {
    myTicketsTitle: "My Tickets",
    exploreEventsButton: "Explore More Events",
    emptyPurchasedEventsTitle: "No event tickets purchased yet!",
    emptyPurchasedEventsSubtitle:
      "No worries - plenty of exciting events to explore!",
    emptyCreatedEventsTitle: "No events have been created yet!",
    emptyCreatedEventsSubtitle: "Go create some now",
    eventsOrganizedTitle: "Events Organized",
    createEventTitle: "Create New Event",
  },
  error: {
    defaultErrorMessage: "Something went wrong.",
  },
};
